site_name: Siddhi-MAP-JSON
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi MAP JSON: index.md
- About:
  - License: about/license.md
- API Docs:
  - 4.0.3-SNAPSHOT: api/4.0.3-SNAPSHOT.md
  - 4.0.4-SNAPSHOT: api/4.0.4-SNAPSHOT.md
theme: material
