site_name: Siddhi-MAP-JSON
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi MAP JSON: index.md
- About:
  - License: about/license.md
- Api:
  - 4.0.3-SNAPSHOT: api/4.0.3-SNAPSHOT.md
- API Docs:
  - 4.0.3-SNAPSHOT: api/4.0.3-SNAPSHOT.md
theme: material
